document.title = 'Homer Simpson - CV'

var title = document.createElement('h1')
title.textContent = document.title
document.body.appendChild(title)

var aboutMeItem = document.createElement('h2')
var aboutMeTitle = document.createTextNode('About me')
aboutMeItem.appendChild(aboutMeTitle)
document.body.appendChild(aboutMeItem)

var introParagraph = document.createElement('p')
var introText = document.createTextNode ('A dedicated and hardworking professional with over 30 years of experience in the manufacturing and quality control industries, Homer Simpson is a results-driven individual known for his loyalty and determination. With expertise in managing high-pressure situations, a natural ability to lead, and a passion for creating lasting relationships with colleagues and customers, Homer brings a unique blend of experience, humor, and commitment to any role. Always ready to tackle new challenges, he thrives in fast-paced environments and aims to contribute to the success of any team he joins.')
introParagraph.appendChild(introText)
document.body.appendChild(introParagraph)

var contactTitle = document.createElement('h2')
var contactText = document.createTextNode('Contact')
contactTitle.appendChild(contactText)
document.body.appendChild(contactTitle)

var contactList = document.createElement('ul')

var emailItem = document.createElement('li')
var emailTitle = document.createElement('strong')
var emailTitleText = document.createTextNode('E-mail:')
emailTitle.appendChild(emailTitleText)
emailItem.appendChild(emailTitle)
var emailSpaceText = document.createTextNode(' ')
emailItem.appendChild(emailSpaceText)
var emailLink = document.createElement('a')
emailLink.href = 'mailto:homersipmson@gmail.com'
var contactEmail = document.createTextNode('homersipmson@gmail.com')
emailLink.appendChild(contactEmail)
emailItem.appendChild(emailLink)
contactList.appendChild(emailItem)

var contactPhone = document.createElement('li')
var phoneTitle = document.createElement('strong')
var phoneTitleText = document.createTextNode('Phone: ')
phoneTitle.appendChild(phoneTitleText)
contactPhone.appendChild(phoneTitle)
var phoneNumber = document.createTextNode('+1 123 456 789')
var phoneLink = document.createElement('a')
phoneLink.href = 'tel:+1123456789'
phoneLink.appendChild(phoneNumber)
contactPhone.appendChild(phoneLink)
contactList.appendChild(contactPhone)

var gitHubItem = document.createElement('li')
var gitHubTitle = document.createElement('strong')
var gitHubTitleText = document.createTextNode('GitHub: ')
gitHubTitle.appendChild(gitHubTitleText)
gitHubItem.appendChild(gitHubTitle)
var gitHubUser = document.createTextNode('H0mer_S1mp')
gitHubItem.appendChild(gitHubUser)
contactList.appendChild(gitHubItem)

var linkedInItem = document.createElement('li')
var linkedInTitle = document.createElement('strong')
var linkedInTitleText = document.createTextNode('LinkedIn: ')
linkedInTitle.appendChild(linkedInTitleText)
linkedInItem.appendChild(linkedInTitle)
var linkedInUser = document.createTextNode('Homer Simpson')
linkedInItem.appendChild(linkedInUser)
contactList.appendChild(linkedInItem)

document.body.appendChild(contactList)

var educationItem = document.createElement('h2')
var educationTitle = document.createTextNode('Education')
educationItem.appendChild(educationTitle)
document.body.appendChild(educationItem)

var uniItem = document.createElement('p')
var uniItemTitle = document.createElement('strong')
var uniItemTitleText = document.createTextNode('Springfield University')
uniItemTitle.appendChild(uniItemTitleText)
uniItem.appendChild(uniItemTitle)
document.body.appendChild(uniItem)

var uniYears = document.createElement('p')
var uniYearsText = document.createTextNode('February 1986 - March 1992')
uniYears.appendChild(uniYearsText)
document.body.appendChild(uniYears)

var workExperience = document.createElement('h2')
var workExperienceTitle = document.createTextNode('Work Experience')
workExperience.appendChild(workExperienceTitle)
document.body.appendChild(workExperience)

var job1 = document.createElement('p')
var job1Title = document.createElement('strong')
var job1TitleText = document.createTextNode('Krusty Burger Manager')
job1Title.appendChild(job1TitleText)
job1.appendChild(job1Title)
document.body.appendChild(job1)
var job1Years = document.createElement('p')
var job1YearsText = document.createTextNode('September 1988 - August 1995')
job1Years.appendChild(job1YearsText)
document.body.appendChild(job1Years)
var job1Info = document.createElement('p')
var job1InfoText = document.createTextNode('A burger restaurant manager oversees daily operations, ensuring quality food, customer satisfaction, and staff coordination. They handle inventory, staff training, and maintain health and safety standards. Additionally, they manage budgets, promotions, and resolve customer complaints.')
job1Info.appendChild(job1InfoText)
document.body.appendChild(job1Info)

var job2 = document.createElement('p')
var job2Title = document.createElement('strong')
var job2TitleText = document.createTextNode('Safety Operations Supervisor')
job2Title.appendChild(job2TitleText)
job2.appendChild(job2Title)
document.body.appendChild(job2)
var job2Years = document.createElement('p')
var job2YearsText = document.createTextNode('February 1996 - Present')
job2Years.appendChild(job2YearsText)
document.body.appendChild(job2Years)
var job2Info = document.createElement('p')
var job2InfoText = document.createTextNode('responsible for overseeing and ensuring the safety standards within the workplace. His role involves assessing potential hazards, conducting safety audits, and implementing safety protocols to minimize risks to employees. He also ensures that all safety equipment is functioning properly and up to code.')
job2Info.appendChild(job2InfoText)
document.body.appendChild(job2Info)

var skills = document.createElement('h2')
var skillsTitle = document.createTextNode('Skills')
skills.appendChild(skillsTitle)
document.body.appendChild(skills)

var skillsList = document.createElement('ul')

var skill1 = document.createElement('li')
var skill1Text = document.createTextNode('Expert foodie')
skill1.appendChild(skill1Text)
skillsList.appendChild(skill1)

var skill2 = document.createElement('li')
var skill2Text = document.createTextNode('Beer taster')
skill2.appendChild(skill2Text)
skillsList.appendChild(skill2)

var skill3 = document.createElement('li')
var skill3Text = document.createTextNode('Master of napping')
skill3.appendChild(skill3Text)
skillsList.appendChild(skill3)